export const site = { name: 'VS Infosys', url: 'https://vsinfosys.in', location: 'Delhi, India' };

export type Detail = { slug: string; title: string; eyebrow: string; summary: string; problems: string[]; keywords: string[] };

export const services: Detail[] = [
  { slug: 'ecommerce-development', title: 'E-commerce development', eyebrow: 'Commerce systems', summary: 'Conversion-minded online stores and commerce journeys designed to make discovery, decisions and operations clearer.', problems: ['Storefronts that feel slow or hard to manage', 'Product journeys that leave buyers uncertain', 'Commerce systems that need to grow with the business'], keywords: ['ecommerce website development Delhi', 'Shopify development', 'ecommerce SEO', 'D2C website design'] },
  { slug: 'website-design-development', title: 'Website design & development', eyebrow: 'Digital presence', summary: 'High-performance websites that explain value clearly, guide the next action and give teams a reliable foundation to grow.', problems: ['An outdated or unclear digital presence', 'Low-quality mobile experience', 'Content that is difficult to maintain'], keywords: ['website design and development Delhi', 'web development company Delhi', 'responsive website design', 'SEO friendly website'] },
  { slug: 'mobile-app-development', title: 'Mobile app development', eyebrow: 'Connected products', summary: 'Useful mobile experiences, customer portals and operational products shaped around real business workflows.', problems: ['Manual processes that need a better interface', 'Customers who need a simpler self-service journey', 'Teams that need connected operational visibility'], keywords: ['mobile app development Delhi', 'app development company India', 'business app development', 'customer portal development'] },
  { slug: 'digital-marketing', title: 'Digital marketing', eyebrow: 'Demand systems', summary: 'Search, content and campaign systems designed to build qualified visibility rather than short-lived attention.', problems: ['Demand that depends too heavily on one channel', 'Search visibility without commercial relevance', 'Content that does not answer buyer questions'], keywords: ['digital marketing agency Delhi', 'SEO services Delhi', 'content marketing India', 'technical SEO services'] },
];

export const industries: Detail[] = [
  { slug: 'real-estate', title: 'Real estate', eyebrow: 'Industry focus', summary: 'Clearer property discovery, lead qualification and trust-led digital journeys for modern real-estate businesses.', problems: ['Complex property information', 'High-intent lead capture', 'Mobile-first enquiry flows'], keywords: ['real estate website development', 'real estate web design Delhi', 'property lead generation', 'real estate digital marketing'] },
  { slug: 'education', title: 'Education & EdTech', eyebrow: 'Industry focus', summary: 'Program discovery, learner journeys and content systems that help education teams explain value before enrolment.', problems: ['Course comparison', 'Lead nurturing', 'Learning platform journeys'], keywords: ['education website design Delhi', 'edtech website development', 'learning platform development', 'education digital marketing'] },
  { slug: 'travel-tourism', title: 'Tour & travel', eyebrow: 'Industry focus', summary: 'Information-rich travel experiences that make itineraries, trust signals and enquiries easier to explore on every screen.', problems: ['Destination and package discovery', 'Mobile booking enquiries', 'Trust-building content'], keywords: ['travel website development India', 'tourism website design', 'travel booking website', 'travel digital marketing'] },
  { slug: 'ecommerce-d2c', title: 'E-commerce & D2C', eyebrow: 'Industry focus', summary: 'Digital commerce systems for brands that need product clarity, conversion confidence and operational flexibility.', problems: ['Product discovery', 'Checkout confidence', 'Retention journeys'], keywords: ['D2C website development', 'ecommerce development Delhi', 'Shopify store development', 'ecommerce conversion optimization'] },
  { slug: 'nonprofits-ngos', title: 'NGOs & social impact', eyebrow: 'Industry focus', summary: 'Accessible storytelling, supporter journeys and practical digital systems for organisations working toward measurable impact.', problems: ['Mission communication', 'Donation and volunteer journeys', 'Accessible public information'], keywords: ['NGO website development India', 'nonprofit website design', 'donation website development', 'NGO digital marketing'] },
];

export const technologies = ['React', 'Next.js', 'Node.js', 'MongoDB', 'ASP.NET Core', 'TypeScript', 'Cloudflare', 'Shopify', 'WordPress'];

export const findDetail = (collection: Detail[], slug: string) => collection.find(item => item.slug === slug);
