#!/usr/bin/env python3
"""Build static inner pages. Python is a build-time utility only; production runtime is HTML/CSS/JS/PHP-compatible."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]

HUBS = [
  dict(slug="websites", title="Websites built to communicate and grow.", label="Websites", desc="Strategy, content, design and development connected into a fast, responsive and maintainable digital presence.", color="var(--orange)", services=[("Web design & development","web-design-development"),("Dynamic websites","dynamic-websites"),("WordPress development","wordpress"),("Domain & hosting","domain-hosting")], outcomes=["Explain the business clearly","Create a confident next action","Work across real devices","Support search and future content"], deliverables=["Discovery and scope","Content structure","UX and interface design","Responsive development","SEO foundations","Launch configuration"], faq=[("Can an existing website be redesigned?","Yes. The current content, search visibility, analytics and technical constraints can be reviewed before defining the new structure."),("Will the website be editable?","The editing approach is selected around the team. Options include a custom WordPress theme or controlled PHP/static workflows."),("Is domain and hosting included?","Selection, DNS, deployment and hosting configuration can be included according to scope.")]),
  dict(slug="commerce", title="Commerce designed around confident decisions.", label="Commerce", desc="Product discovery, information and purchase flows designed to reduce friction while keeping operations practical.", color="var(--pink)", services=[("E-commerce development","ecommerce"),("Shopify development","shopify"),("WordPress & WooCommerce","wordpress"),("Commerce applications","app-development")], outcomes=["Make products easier to discover","Clarify value and comparison","Reduce checkout friction","Support content and campaigns"], deliverables=["Commerce requirements","Journey and catalogue structure","Product interface system","Platform setup","Payment/shipping integration","Launch testing"], faq=[("Shopify or WooCommerce?","The answer depends on catalogue complexity, internal skills, integrations, hosting preference and expected customization."),("Can content and product graphics be included?","Yes. Product copy, graphics and campaign assets can be scoped with the commerce experience."),("Can an existing store be improved?","Yes. UX, performance, content structure, SEO and operational friction can be reviewed independently or together.")]),
  dict(slug="growth", title="Visibility built on useful foundations.", label="Growth", desc="SEO, content and digital marketing aligned with what people need and what the business can genuinely deliver.", color="var(--lime)", services=[("SEO services","seo"),("Digital marketing","digital-marketing"),("Content writing","content-writing"),("Web improvement","web-design-development")], outcomes=["Strengthen technical foundations","Map search intent to useful pages","Connect campaigns and landing pages","Measure meaningful actions"], deliverables=["Search opportunity review","Technical and on-page plan","Content architecture","Campaign direction","Measurement setup","Improvement backlog"], faq=[("Can ranking be guaranteed?","No responsible provider can guarantee a position. The work improves technical quality, relevance, usefulness and measurement while search systems remain outside anyone’s control."),("Is SEO included with a website?","Technical and on-page foundations are included in the build standard. Ongoing content and authority work are separate growth activities."),("Will AI write articles automatically?","AI may assist research and structure, but low-value automated publishing is not part of the approach. Originality and human approval remain required.")]),
  dict(slug="content", title="One clear idea, expressed in every format.", label="Content", desc="Writing, graphics and video systems that keep the message consistent across the website, search and campaigns.", color="var(--violet)", services=[("Content writing","content-writing"),("Graphic design","graphic-design"),("Video generation","video-generation"),("Content-led websites","web-design-development")], outcomes=["Create a consistent message","Adapt ideas for each channel","Support search with useful content","Give campaigns a coherent visual language"], deliverables=["Message direction","Content architecture","Web and campaign copy","Graphic system","Video concepts/assets","Publishing guidance"], faq=[("Can content be created before the website?","Yes. Message and content structure often improve the quality of the website design process."),("Is AI-generated content used?","Tools can support research, drafting and production, but final content must be accurate, useful and approved."),("Can one engagement include writing, graphics and video?","Yes. A shared concept can be planned across formats for consistency.")]),
  dict(slug="ai", title="AI connected to practical work.", label="Practical AI", desc="Human-guided automation for knowledge, qualification, content workflows and repetitive processes.", color="var(--cyan)", services=[("AI implementation","ai-implementation"),("Custom applications","app-development"),("Workflow systems","app-development"),("Content workflows","content-writing")], outcomes=["Identify useful automation opportunities","Connect trusted knowledge","Keep human review where it matters","Measure time and quality impact"], deliverables=["Workflow discovery","Opportunity and risk map","Prototype","Knowledge/data preparation","Implementation","Testing and handover"], faq=[("Where should AI be used first?","Start with a repeated, well-understood process where inputs, decisions and acceptable outputs can be clearly described."),("Does AI replace human review?","Not by default. Review and escalation should remain wherever accuracy, sensitivity or business judgment requires them."),("Can AI connect to an existing website?","Potentially. The integration depends on the platform, data access, security and the exact workflow.")]),
  dict(slug="applications", title="Systems shaped around the people using them.", label="Applications", desc="Portals, dashboards and custom workflows designed to make complex operations clearer and easier to maintain.", color="var(--gold)", services=[("App development","app-development"),("Dynamic websites","dynamic-websites"),("AI implementation","ai-implementation"),("Custom PHP systems","app-development")], outcomes=["Reduce repeated manual work","Create a clearer operational view","Connect data and actions","Support controlled future changes"], deliverables=["Workflow and role mapping","Information architecture","Interface system","Application development","Integration and testing","Documentation"], faq=[("Can this run on shared hosting?","Some PHP/MySQL applications can. Hosting is selected after understanding processing, security, storage and integration requirements."),("Can an internal dashboard be mobile-friendly?","Yes. Responsive priorities are defined around the tasks each role performs on different devices."),("Can an existing process be prototyped first?","Yes. A focused prototype can validate the workflow before a complete system is built.")]),
]

DETAILS = [
 dict(slug="web-design-development", title="Web design and development that makes the business clear.", label="Web design & development", desc="A connected process for content structure, responsive interface design, custom development and launch quality.", color="var(--orange)", outcomes=["A clear value proposition and page hierarchy","Responsive UX designed for real devices","Semantic, search-ready HTML","A maintainable shared-hosting solution"], deliverables=["Discovery and page strategy","Sitemap and content structure","Wireframes and UI system","Custom HTML/CSS/JavaScript or approved CMS build","Responsive QA","Launch and handover"], related=[("Dynamic websites","dynamic-websites"),("WordPress","wordpress"),("SEO services","seo")], faq=[("Why use custom CSS instead of a framework?","Custom CSS can reduce unused code and preserve a distinctive design system when the project benefits from that control."),("Will the site work without JavaScript?","Essential content and links should remain accessible in semantic HTML; JavaScript enhances interaction."),("Can the site move to different hosting later?","A static or standard PHP architecture is portable across many shared and business hosting providers.")]),
 dict(slug="dynamic-websites", title="Dynamic websites without unnecessary infrastructure.", label="Dynamic website development", desc="Websites with forms, structured content and business logic selected around affordable shared or business hosting.", color="var(--cyan)", outcomes=["Content and features matched to real operating needs","PHP/MySQL options for shared hosting","Clear separation of presentation and data","A practical maintenance path"], deliverables=["Feature and data planning","Template architecture","Frontend design system","PHP/CMS implementation where required","Security and validation","Deployment documentation"], related=[("Web design","web-design-development"),("WordPress","wordpress"),("App development","app-development")], faq=[("Does dynamic always mean a database?","No. A database is added only when content relationships, accounts or workflows genuinely require one."),("Can a dynamic site use shared hosting?","Yes, when the selected PHP/MySQL features fit the hosting limits and security requirements."),("Will it still be search-friendly?","Indexable pages should render meaningful HTML, use stable URLs and follow the same on-page and technical standards.")]),
 dict(slug="wordpress", title="WordPress shaped around your content—not a generic theme.", label="WordPress development", desc="Custom WordPress experiences for teams that need familiar editing without sacrificing interface quality or performance discipline.", color="var(--violet)", outcomes=["A controlled editing experience","Custom frontend rather than a generic theme look","Reduced plugin dependence","Search and performance foundations"], deliverables=["Content model","Custom theme/UI","Editor configuration","Plugin and security review","Caching and optimization","Training and launch"], related=[("Web design","web-design-development"),("WooCommerce","ecommerce"),("Domain & hosting","domain-hosting")], faq=[("Will you use a pre-built theme?","The preferred approach is a custom theme or carefully controlled foundation aligned to the approved design."),("How many plugins will be installed?","Only justified, maintained plugins. Unnecessary plugin stacks increase security, performance and maintenance risk."),("Can WooCommerce be included?","Yes, when WooCommerce fits the catalogue, operations and hosting environment.")]),
 dict(slug="domain-hosting", title="Domain and hosting decisions made for the website you actually need.", label="Domain & hosting", desc="Practical support for registration, DNS, email, SSL, deployment, backups and hosting selection.", color="var(--gold)", outcomes=["Correct ownership and access","A hosting plan matched to the build","Secure HTTPS and reliable DNS","A documented deployment and backup path"], deliverables=["Domain/DNS review","Hosting recommendation","SSL and email coordination","Deployment","Caching/security baseline","Access and renewal documentation"], related=[("Web design","web-design-development"),("WordPress","wordpress"),("Dynamic websites","dynamic-websites")], faq=[("Who owns the domain?","The business should own and control its domain account. Access can be granted for configuration without transferring ownership."),("Is the cheapest hosting always suitable?","No. The right choice depends on traffic, PHP limits, email, backups, security and application requirements."),("Can an existing domain be retained?","Yes. DNS can usually be updated while preserving ownership and, with planning, existing email services.")]),
 dict(slug="ecommerce", title="E-commerce experiences designed to reduce buying friction.", label="E-commerce development", desc="Catalogue, product, cart and checkout experiences connected to practical store operations.", color="var(--pink)", outcomes=["Clear product discovery and comparison","Confident product-detail decisions","Less friction through cart and checkout","Content and SEO-ready catalogue structure"], deliverables=["Commerce requirements","Catalogue architecture","Responsive store UI","Platform implementation","Payment/shipping setup","Testing and launch"], related=[("Shopify","shopify"),("WordPress","wordpress"),("Digital marketing","digital-marketing")], faq=[("Which payment gateway can be used?","The choice depends on business eligibility, location, currencies, fees and platform support."),("Can product upload be included?","Yes. The catalogue size, data quality and media preparation determine the scope."),("Is SEO different for e-commerce?","Commerce SEO adds catalogue architecture, product/category duplication, structured data and crawl-control considerations.")]),
 dict(slug="shopify", title="Shopify storefronts with a clearer brand and buying journey.", label="Shopify development", desc="Theme customization, custom storefront sections and commerce setup for teams that prefer a managed platform.", color="var(--lime)", outcomes=["A storefront aligned to the brand","Manageable product and content sections","Mobile-first purchase journeys","A focused app and performance setup"], deliverables=["Store requirements","Theme and section system","Product/catalogue setup","App evaluation","Payment/shipping configuration","Launch QA"], related=[("E-commerce","ecommerce"),("Content writing","content-writing"),("Digital marketing","digital-marketing")], faq=[("Will a paid theme be required?","Not always. The decision depends on features, budget and how much custom interface work is needed."),("Can an existing Shopify store be redesigned?","Yes. Theme structure, apps, content, navigation and conversion friction can be reviewed."),("How are apps selected?","Each app should solve a real requirement without duplicating features or creating unjustified performance cost.")]),
 dict(slug="seo", title="SEO built around relevance, usefulness and technical health.", label="SEO services", desc="A sustainable system for crawlability, search intent, helpful pages, internal links and continuous measurement.", color="var(--lime)", outcomes=["A crawlable and indexable technical foundation","A query-to-page architecture","Useful commercial and supporting content","A measured opportunity and improvement loop"], deliverables=["Technical audit","Keyword and intent map","On-page recommendations","Internal-link plan","Content backlog","Search Console reporting"], related=[("Digital marketing","digital-marketing"),("Content writing","content-writing"),("Web design","web-design-development")], faq=[("Can you guarantee first position?","No. Search systems and competitors are outside any provider’s control. The work focuses on controllable quality and measured improvement."),("How long does SEO take?","Technical changes may be discovered quickly, while competitive visibility often develops over months. Timing varies by query, authority and execution."),("Will pages be generated automatically?","Not at scale for ranking manipulation. Automation supports checks and briefs; useful original content requires review.")]),
 dict(slug="digital-marketing", title="Digital marketing connected to the page people land on.", label="Digital marketing", desc="Campaign direction, landing experiences, content and measurement treated as one conversion system.", color="var(--cyan)", outcomes=["Clear campaign and audience alignment","Landing pages matched to intent","Consistent campaign creative","Measurement tied to meaningful actions"], deliverables=["Audience and offer review","Channel/campaign plan","Landing page direction","Creative/content requirements","Tracking setup","Optimization backlog"], related=[("SEO","seo"),("Content writing","content-writing"),("Graphic design","graphic-design")], faq=[("Which channels should be used?","Channel choice follows the audience, offer, buying cycle, creative capacity and measurement—not a default package."),("Are advertising budgets included?","Media spend is normally separate from strategy, creative, setup and management fees."),("Can landing pages be developed too?","Yes. Campaign and landing experience should be planned together whenever possible.")]),
 dict(slug="content-writing", title="Content that helps people understand and decide.", label="Content writing", desc="Website, service and guide content structured around real questions, clear language and useful next actions.", color="var(--violet)", outcomes=["A consistent message and voice","Clear service explanations","Search-aligned helpful resources","Content that supports conversion without hype"], deliverables=["Message and audience review","Page outlines","Website/service copy","Guide content","SEO/editorial review","Publishing-ready files"], related=[("SEO","seo"),("Graphic design","graphic-design"),("Web design","web-design-development")], faq=[("Will content be written only for keywords?","No. Search terms help reveal language and intent, but the content must satisfy people first."),("Can existing content be improved?","Yes. Existing pages can be restructured, clarified, consolidated or expanded based on their job."),("Is AI used in writing?","It may assist research and drafting, but accuracy, originality, voice and final approval remain human responsibilities.")]),
 dict(slug="graphic-design", title="Graphic systems that make the message easier to recognize.", label="Graphic design", desc="Visual direction and digital assets designed to support websites, content and campaigns consistently.", color="var(--pink)", outcomes=["A more coherent digital visual language","Clearer hierarchy and communication","Reusable campaign/content assets","Graphics optimized for their actual channels"], deliverables=["Visual direction","Graphic system","Web graphics","Campaign/social assets","Export variants","Usage guidance"], related=[("Content writing","content-writing"),("Video generation","video-generation"),("Web design","web-design-development")], faq=[("Can graphics be created without brand guidelines?","Yes. A focused visual direction can be established, though a complete brand identity is a larger separate scope."),("Will source files be provided?","Handover formats and editable source requirements should be defined in the project scope."),("Are graphics optimized for the web?","Digital exports should be sized and compressed for their actual placement and performance needs.")]),
 dict(slug="video-generation", title="Video concepts built around a message—not motion for its own sake.", label="Video generation", desc="Storyboards, generated visuals and motion assets for websites, campaigns and content systems.", color="var(--gold)", outcomes=["A clear narrative before production","Visual consistency with the wider brand","Channel-appropriate formats","Performance-aware website motion assets"], deliverables=["Concept and script direction","Storyboard","Visual generation","Editing/motion","Format variants","Web delivery optimization"], related=[("Graphic design","graphic-design"),("Content writing","content-writing"),("Digital marketing","digital-marketing")], faq=[("Can generated video be used as a website background?","It can, but only when the value justifies the performance cost and accessible static alternatives are provided."),("Will the output be cinematic?","Art direction, pacing, source quality and editing determine the result more than the generation tool alone."),("Can multiple formats be delivered?","Yes. Aspect ratios, duration and compression should be planned for each channel.")]),
 dict(slug="ai-implementation", title="AI implementation grounded in a real workflow.", label="AI implementation", desc="Opportunity mapping, prototyping and integration for processes where assistance can create measurable practical value.", color="var(--cyan)", outcomes=["A prioritized opportunity map","Clear human-review boundaries","A testable workflow prototype","Implementation matched to security and data constraints"], deliverables=["Process discovery","Use-case and risk assessment","Prototype","Knowledge/data preparation","Integration","Testing and documentation"], related=[("App development","app-development"),("Content writing","content-writing"),("Dynamic websites","dynamic-websites")], faq=[("What information is needed to assess an AI use case?","The current steps, inputs, decisions, exceptions, data access and acceptable error boundaries must be understood."),("Can sensitive data be used?","Only after privacy, provider terms, storage, access and security requirements are evaluated."),("Does every business need custom AI?","No. Sometimes a process change or existing tool solves the problem more safely and cheaply.")]),
 dict(slug="app-development", title="Applications designed around tasks, roles and maintainability.", label="App development", desc="Responsive portals, dashboards and workflow tools built with an architecture appropriate for shared or business hosting.", color="var(--gold)", outcomes=["Clear user roles and workflows","Less operational friction","Responsive task-focused interfaces","A documented, maintainable technical path"], deliverables=["Requirements and role mapping","Application architecture","UX/UI system","Development","Integration and validation","Deployment and documentation"], related=[("AI implementation","ai-implementation"),("Dynamic websites","dynamic-websites"),("Domain & hosting","domain-hosting")], faq=[("Can an app run on PHP shared hosting?","Some portal and workflow applications can. Real-time, compute-heavy or high-scale requirements may require different infrastructure."),("Will you build Android and iOS apps?","The best format—responsive web app, progressive web app or native app—depends on device features, distribution and offline needs."),("Can the project start with a prototype?","Yes. A focused prototype can validate navigation, workflow and technical assumptions before full implementation.")]),
]

def rel_prefix(slug): return "../../"

def header(prefix, active="Services"):
    return f'''<header class="site-header" data-header><a class="wordmark" href="{prefix}">VS Infosys<span class="wordmark-dot">.</span></a><nav class="desktop-nav" aria-label="Primary"><a href="{prefix}services/">Services</a><a href="{prefix}#method">Approach</a><a href="{prefix}insights/">Insights</a><a href="{prefix}contact/">Contact</a></nav><div class="header-actions"><button class="motion-toggle" type="button" data-motion-toggle aria-pressed="false"><span class="motion-toggle-dot"></span><span data-motion-label>Motion on</span></button><a class="button button-small button-outline" href="{prefix}start-a-project/">Start a project</a><button class="menu-toggle" type="button" data-menu-toggle aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span><span class="sr-only">Open menu</span></button></div><div class="mobile-menu" id="mobile-menu" data-mobile-menu hidden><nav><a href="{prefix}services/">Services</a><a href="{prefix}#method">Approach</a><a href="{prefix}insights/">Insights</a><a href="{prefix}contact/">Contact</a></nav><p>Delhi, India</p></div></header>'''

def footer(prefix):
    return f'''<footer class="site-footer section-dark"><div class="shell footer-grid"><a class="wordmark" href="{prefix}">VS Infosys<span class="wordmark-dot">.</span></a><div><p class="footer-label">Explore</p><a href="{prefix}services/">Services</a><a href="{prefix}#method">Approach</a><a href="{prefix}insights/">Insights</a></div><div><p class="footer-label">Connect</p><a href="{prefix}contact/">Contact</a><a href="{prefix}start-a-project/">Start a project</a></div><div><p class="footer-label">Location</p><p>Delhi, India<br>Working beyond borders</p></div></div><div class="shell footer-bottom"><span>© <span data-year></span> VS Infosys</span><span><a href="{prefix}privacy/">Privacy</a> · <a href="{prefix}terms/">Terms</a></span><span>HTML · CSS · JavaScript</span></div></footer>'''

def head(title, desc, prefix):
    css=['reset','tokens','base','components','sections','color-spirit','inner-pages','motion','responsive']
    links=''.join(f'<link rel="stylesheet" href="{prefix}assets/css/{x}.css">' for x in css)
    return f'''<!doctype html><html lang="en" class="no-js"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#050505"><meta name="description" content="{escape(desc)}"><meta name="robots" content="noindex,nofollow"><title>{escape(title)} — VS Infosys</title>{links}<script>document.documentElement.classList.replace('no-js','js')</script><script type="module" src="{prefix}assets/js/main.js"></script></head>'''

def render_service(page, is_hub=False):
    prefix='../../'; label=escape(page['label']); title=escape(page['title']); desc=escape(page['desc']); color=page['color']
    cards=''.join(f'<article class="reveal"><span></span><h3>{escape(x)}</h3><p>{escape(_outcome_copy(x))}</p></article>' for x in page['outcomes'])
    deliver=''.join(f'<li><span>{i:02}</span>{escape(x)}</li>' for i,x in enumerate(page['deliverables'],1))
    faqs=''.join(f'<article><h3><button type="button" aria-expanded="false">{escape(q)}<span>+</span></button></h3><div class="accordion-panel" hidden><p>{escape(a)}</p></div></article>' for q,a in page['faq'])
    if is_hub:
        related=''.join(f'<a href="../{slug}/"><span>Explore</span><strong>{escape(name)}</strong><i>↗</i></a>' for name,slug in page['services'])
        relation_title='Explore the connected services'
    else:
        related=''.join(f'<a href="../{slug}/"><span>Related</span><strong>{escape(name)}</strong><i>↗</i></a>' for name,slug in page['related'])
        relation_title='Continue with a related capability'
    kind='Capability hub' if is_hub else 'Service'
    html=head(f"{label} in Delhi",page['desc'],prefix)+f'''<body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><div class="page-progress"><span data-page-progress></span></div><div class="grain"></div>{header(prefix)}<main id="main-content" class="inner-main service-detail" style="--page-color:{color}">
<section class="detail-hero"><div class="detail-aura"></div><div class="shell breadcrumb"><a href="{prefix}">Home</a><span>/</span><a href="../">Services</a><span>/</span><span>{label}</span></div><div class="shell detail-hero-grid"><div><p class="section-index reveal">{kind} · Delhi</p><h1>{title}</h1></div><div class="detail-summary reveal"><p>{desc}</p><a class="button button-light" href="#scope">Explore the approach <span>↓</span></a></div></div></section>
<section class="detail-outcomes section-light"><div class="shell"><p class="section-index">What this should achieve</p><div class="detail-outcome-grid">{cards}</div></div></section>
<section class="detail-approach section-dark" id="scope"><div class="shell detail-two-col"><div><p class="section-index">The approach</p><h2 class="section-title reveal">Start with the job.<br>Choose technology after.</h2><p class="large-copy reveal">The scope is shaped around users, content, operations, hosting and the action the experience needs to make easier.</p></div><div class="meaning-graphic reveal" aria-hidden="true"><div class="meaning-core"></div><i></i><i></i><i></i><span>Need</span><span>System</span><span>Outcome</span></div></div></section>
<section class="detail-scope section-light"><div class="shell detail-two-col"><div><p class="section-index">What the engagement can include</p><h2 class="section-title reveal">A complete path to launch.</h2></div><ol class="scope-list">{deliver}</ol></div></section>
<section class="detail-process section-dark"><div class="shell"><p class="section-index">A clear delivery rhythm</p><div class="detail-process-grid"><article><span>Discover</span><p>Understand the context, users and objective.</p></article><article><span>Define</span><p>Agree on structure, scope and technical direction.</p></article><article><span>Design</span><p>Shape the experience and visual system.</p></article><article><span>Build</span><p>Develop, integrate, test and refine.</p></article><article><span>Evolve</span><p>Launch, measure and improve.</p></article></div></div></section>
<section class="detail-related section-light"><div class="shell"><p class="section-index">{relation_title}</p><div class="related-links">{related}</div></div></section>
<section class="detail-faq section-light"><div class="shell detail-two-col"><div><p class="section-index">Questions before starting</p><h2 class="section-title reveal">Useful answers,<br>before the first call.</h2></div><div class="accordion" data-accordion>{faqs}</div></div></section>
<section class="inner-cta"><div class="shell"><p class="section-index">Start with the outcome</p><h2 class="reveal">Ready to shape<br><em>the next step?</em></h2><a class="button button-light" href="{prefix}start-a-project/">Start a project <span>↗</span></a></div></section></main>{footer(prefix)}</body></html>'''
    return html

def _outcome_copy(title):
    mapping={
      "A clear value proposition and page hierarchy":"Help visitors understand the business and navigate with confidence.","Responsive UX designed for real devices":"Keep the experience intentional across screens and inputs.","Semantic, search-ready HTML":"Make essential content accessible to people and crawlers.","A maintainable shared-hosting solution":"Match the architecture to practical operating costs.",
      "Content and features matched to real operating needs":"Avoid complexity that does not improve the business workflow.","PHP/MySQL options for shared hosting":"Use infrastructure appropriate to the budget and requirement.","Clear separation of presentation and data":"Keep future changes understandable.","A practical maintenance path":"Document how the site is operated after launch.",
    }
    return mapping.get(title,title+" through a connected, clearly defined delivery approach.")

def plan_doc(page, order, kind):
    return f'''# Page {order:02} — {page['label']}\n\n**Status:** Planned, designed, SEO-reviewed, built and architecture-verified  \n**Route:** `/services/{page['slug']}/`  \n**Type:** {kind}\n\n## Search intent\n\nA commercial visitor evaluating {page['label'].lower()} support from a Delhi-based digital technology company. Exact query targets require Phase 1 keyword validation.\n\n## Sections\n\n1. Search-aligned cinematic hero\n2. Outcome grid\n3. Approach and meaningful system graphic\n4. Deliverable scope\n5. Delivery process\n6. Related capabilities\n7. Buyer FAQ\n8. Project CTA\n\n## SEO and quality verification\n\n- One H1\n- Unique title and description\n- Semantic HTML and crawlable related links\n- Natural Delhi context\n- No fabricated proof or ranking promises\n- Custom CSS and dependency-free JavaScript\n- Responsive and reduced-motion compatible\n- Prototype remains noindex until production details are verified\n'''

def write_page(page, is_hub, order):
    dest=ROOT/'services'/page['slug']/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(render_service(page,is_hub))
    plan=ROOT/'project-management'/'pages'/f'{order:02}-{page["slug"]}.md';plan.write_text(plan_doc(page,order,'Capability hub' if is_hub else 'Detailed service page'))

if __name__=='__main__':
    order=2
    for item in HUBS: write_page(item,True,order);order+=1
    for item in DETAILS: write_page(item,False,order);order+=1
    print(f'Built {len(HUBS)+len(DETAILS)} static service pages.')
