#!/usr/bin/env python3
from pathlib import Path
from html import escape
from build_pages import ROOT, head, header, footer

PAGES = {
"about": dict(title="A digital partner built around the work.", label="About VS Infosys", desc="VS Infosys is a Delhi-based digital technology company connecting strategy, design, content, development and growth.", sections=[("What matters","A digital experience should make a business easier to understand, easier to choose and easier to operate. That requires more than a visual layer. It requires clear content, intentional structure, suitable technology and a plan for what happens after launch."),("How we approach the work","We begin with the business context and user task. Design, platform and motion decisions follow. This keeps the solution focused on the job instead of a fashionable stack or a collection of disconnected deliverables."),("What we bring together","Web design and development, commerce, SEO, digital marketing, content, graphics, video, AI implementation and applications can be planned as connected capabilities or focused stages."),("Delhi roots, broader delivery","VS Infosys is based in Delhi and can work with businesses beyond the region through a documented, digital-first project process. Exact office and service-area details will be added after business verification.")]),
"contact": dict(title="Start with a clear conversation.", label="Contact", desc="Contact VS Infosys in Delhi to discuss a website, commerce, SEO, content, AI or application project.", sections=[]),
}

GUIDES = [
 dict(slug="wordpress-shopify-custom-website", title="Custom website, WordPress or Shopify: how to choose", desc="A practical comparison of custom static websites, WordPress and Shopify for business owners planning a new digital presence.", read="10 min", body=[
 ("Start with the operating model—not the platform","The right platform depends on what the website must do, who will update it, how often it changes, where it will be hosted and what the business can maintain. Choosing only from popularity can create unnecessary cost later."),
 ("Choose a custom static website when","A custom HTML, CSS and JavaScript website can be an excellent fit when speed, portability, distinctive design and low hosting cost matter more than frequent non-technical editing. It has a small attack surface and can run on inexpensive static or shared hosting. Content updates need a controlled editing or deployment process."),
 ("Choose WordPress when","WordPress is useful when a team needs familiar browser-based editing, structured publishing and a large ecosystem. It works well on standard PHP/MySQL hosting, but theme quality, plugin discipline, caching and maintenance directly affect performance and security."),
 ("Choose Shopify when","Shopify is designed for managed commerce. It is often suitable when catalogue, checkout, payments and store operations are the centre of the project. Monthly platform and app costs should be evaluated alongside the reduced infrastructure responsibility."),
 ("Questions to decide","Who will update content? Is checkout required? Are custom workflows essential? What is the hosting budget? How important is platform portability? Which integrations are mandatory? The answer should emerge from these constraints."),
 ("A practical conclusion","There is no universally best platform. A smaller, well-matched system usually outperforms a larger system the team cannot operate confidently.")]),
 dict(slug="website-project-checklist", title="What should a business prepare before starting a website?", desc="A practical website project checklist covering goals, audience, content, domain, hosting, functionality and measurement.", read="9 min", body=[
 ("Define the business action","Decide what the website should help a visitor do: understand a service, request a proposal, buy a product, book a conversation or use a tool. One primary action creates a stronger foundation for structure and content."),
 ("Describe the audience","List the people the website must serve, what they already know, the questions they ask and what could prevent them from acting. Avoid defining an audience as everyone."),
 ("Collect business facts","Prepare the official name, contact details, service area, business hours, service list, process, policies and any claims that can be verified. Missing facts should remain missing rather than being invented."),
 ("Inventory content and assets","Collect existing copy, documents, logos, photographs, videos, product information and old URLs. Mark what is current, what needs revision and what does not exist yet."),
 ("List functional requirements","Forms, commerce, logins, dashboards, calculators, languages and integrations affect architecture. Separate essential launch requirements from later improvements."),
 ("Secure access and ownership","The business should control the domain, hosting, analytics and platform accounts. Record renewals and recovery methods."),
 ("Agree on measurement","Choose useful outcomes such as qualified enquiries, purchases, booked calls or completed tasks. Total traffic alone does not define success.")]),
 dict(slug="practical-ai-automation", title="Where can AI save time—and where should it not be used?", desc="A practical framework for finding responsible AI automation opportunities in small and medium business workflows.", read="11 min", body=[
 ("Begin with a repeated process","The strongest starting point is usually a process that happens frequently, follows understandable steps and consumes time through classification, retrieval, drafting or routing."),
 ("Map inputs, decisions and exceptions","Document what enters the process, which decisions are made, where information comes from and what unusual cases look like. If the process cannot be explained, automating it may make the confusion faster."),
 ("Keep human review where consequences matter","Financial, legal, medical, safety, privacy and reputation-sensitive outputs need appropriate control. Human review is also valuable when context and relationship matter more than speed."),
 ("Evaluate data before the model","Check whether the required information is accurate, accessible and permitted for the proposed tool. Security, retention, provider terms and confidentiality should be part of the design."),
 ("Prototype a narrow outcome","Test one clear task before connecting an entire operation. Compare time, quality, error patterns and user confidence with the current process."),
 ("Know when not to automate","Do not automate a rare process with unclear value, a sensitive decision without oversight, or a broken workflow that first needs simplification."),
 ("A useful test","AI is appropriate when it makes a defined task meaningfully easier while keeping quality, privacy and accountability within acceptable boundaries.")]),
]

def inner_head(title,desc,prefix="../"):
    return head(title,desc,prefix)

def shell_page(slug,data):
    prefix="../"; sec=''.join(f'<section class="editorial-section {"light" if i%2==0 else "dark"}"><div class="shell editorial-grid"><p class="section-index">{escape(h)}</p><div class="editorial-copy"><h2 class="section-title reveal">{escape(h)}</h2><p>{escape(p)}</p></div></div></section>' for i,(h,p) in enumerate(data['sections']))
    return inner_head(data['label'],data['desc'])+f'''<body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><div class="page-progress"><span data-page-progress></span></div><div class="grain"></div>{header(prefix)}<main id="main-content" class="inner-main"><section class="editorial-hero"><div class="shell breadcrumb"><a href="../">Home</a><span>/</span><span>{escape(data['label'])}</span></div><div class="shell editorial-hero-grid"><div><p class="section-index reveal">{escape(data['label'])} · Delhi</p><h1>{escape(data['title'])}</h1></div><p class="reveal">{escape(data['desc'])}</p></div></section>{sec}<section class="inner-cta"><div class="shell"><p class="section-index">The next useful step</p><h2 class="reveal">What should we<br><em>build next?</em></h2><a class="button button-light" href="../start-a-project/">Start a project ↗</a></div></section></main>{footer(prefix)}</body></html>'''

def contact_page(start=False):
    prefix='../'; heading='Tell us where you are heading.' if start else 'Start with a clear conversation.'; label='Start a project' if start else 'Contact'; desc='Share the outcome, current situation and the kind of help you are looking for. The prototype form does not transmit personal data yet.'
    return inner_head(label,desc)+f'''<body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><div class="page-progress"><span data-page-progress></span></div><div class="grain"></div>{header(prefix)}<main id="main-content" class="inner-main"><section class="editorial-hero"><div class="shell breadcrumb"><a href="../">Home</a><span>/</span><span>{label}</span></div><div class="shell editorial-hero-grid"><div><p class="section-index reveal">{label} · Delhi</p><h1>{heading}</h1></div><p class="reveal">{desc}</p></div></section><section class="editorial-section dark"><div class="shell contact-page-grid"><div><p class="section-index">Direct contact</p><div class="contact-list"><a href="mailto:hello@example.com"><span>Email</span><strong>hello@example.com</strong></a><a href="#"><span>WhatsApp</span><strong>Add verified number</strong></a><p><span>Location</span><strong>Delhi, India</strong></p></div></div><form class="project-form" data-project-form novalidate><div class="form-step is-active" data-form-step="0"><p><span>01</span>What do you need?</p><div class="choice-grid"><label><input type="radio" name="need" value="website" required><span>Website</span></label><label><input type="radio" name="need" value="commerce"><span>Commerce</span></label><label><input type="radio" name="need" value="growth"><span>Growth</span></label><label><input type="radio" name="need" value="content"><span>Content</span></label><label><input type="radio" name="need" value="ai"><span>AI</span></label><label><input type="radio" name="need" value="app"><span>App / system</span></label></div><button class="button button-light form-next" type="button">Continue →</button></div><div class="form-step" data-form-step="1" hidden><p><span>02</span>Tell us a little more.</p><label class="field"><span>Name</span><input name="name" required autocomplete="name"></label><label class="field"><span>Email</span><input type="email" name="email" required autocomplete="email"></label><label class="field"><span>Project brief</span><textarea name="brief" rows="5" required></textarea></label><div class="form-actions"><button class="text-link form-back" type="button">← Back</button><button class="button button-light" type="submit">Send enquiry ↗</button></div></div><div class="form-status" data-form-status role="status" aria-live="polite"></div></form></div></section></main>{footer(prefix)}</body></html>'''

def insights_index():
    prefix='../'; cards=''.join(f'<article class="guide-card reveal"><small>{g["read"]} · Practical guide</small><h2>{escape(g["title"])}</h2><p>{escape(g["desc"])}</p><a href="{g["slug"]}/">Read the guide →</a></article>' for g in GUIDES)
    return inner_head('Practical digital guides','Practical guides from VS Infosys covering website platforms, project planning and responsible AI automation.')+f'''<body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><div class="page-progress"><span data-page-progress></span></div><div class="grain"></div>{header(prefix)}<main id="main-content" class="inner-main"><section class="editorial-hero"><div class="shell breadcrumb"><a href="../">Home</a><span>/</span><span>Insights</span></div><div class="shell editorial-hero-grid"><div><p class="section-index reveal">Practical guides</p><h1>Useful before <em>the first call.</em></h1></div><p>Decision frameworks for websites, platforms, SEO, content and practical technology—written to make the next step clearer.</p></div></section><section class="guide-index"><div class="shell"><p class="section-index">Latest guides</p><div class="guide-grid">{cards}</div></div></section></main>{footer(prefix)}</body></html>'''

def guide_page(g):
    prefix='../../'; body=''.join(f'<section id="s{i}"><h2>{escape(h)}</h2><p>{escape(p)}</p></section>' for i,(h,p) in enumerate(g['body'],1)); nav=''.join(f'<a href="#s{i}">{escape(h)}</a>' for i,(h,_) in enumerate(g['body'],1))
    return head(g['title'],g['desc'],prefix)+f'''<body class="inner-page"><a class="skip-link" href="#main-content">Skip to content</a><div class="page-progress"><span data-page-progress></span></div><div class="grain"></div>{header(prefix)}<main id="main-content" class="inner-main"><section class="editorial-hero"><div class="shell breadcrumb"><a href="{prefix}">Home</a><span>/</span><a href="../">Insights</a><span>/</span><span>Guide</span></div><div class="shell editorial-hero-grid"><div><p class="section-index reveal">{g['read']} · Practical guide</p><h1>{escape(g['title'])}</h1></div><p>{escape(g['desc'])}</p></div></section><article class="editorial-section light"><div class="shell article-layout"><aside class="article-aside"><p class="section-index">In this guide</p>{nav}</aside><div class="prose"><p class="lead">{escape(g['desc'])}</p>{body}<blockquote>A useful platform or automation decision begins with the work it must support.</blockquote><p>This guide provides general planning information. A final recommendation requires the real business, content, hosting and workflow constraints.</p></div></div></article><section class="inner-cta"><div class="shell"><p class="section-index">Apply the thinking</p><h2>Plan the right<br><em>next step.</em></h2><a class="button button-light" href="{prefix}start-a-project/">Start a project ↗</a></div></section></main>{footer(prefix)}</body></html>'''

def legal_page(kind):
    prefix='../';title='Privacy policy' if kind=='privacy' else 'Terms of use';desc=f'Draft {title.lower()} for the VS Infosys website. Legal review is required before production publication.'
    body='<div class="legal-note"><strong>Draft only.</strong> This page must be reviewed against the final business entity, hosting, analytics, form and service practices before launch.</div>'
    topics=['Information the website collects','How information may be used','Cookies and analytics','Data retention and security','Contact and user rights'] if kind=='privacy' else ['Website information','Project enquiries','Intellectual property','External services and links','Limitations and updates']
    body+=''.join(f'<h2>{escape(x)}</h2><p>Production wording will be completed after the relevant business, data and service practices are confirmed. No placeholder clause should be treated as legal advice.</p>' for x in topics)
    return inner_head(title,desc)+f'''<body class="inner-page">{header(prefix)}<main id="main-content" class="inner-main"><section class="editorial-hero"><div class="shell breadcrumb"><a href="../">Home</a><span>/</span><span>{title}</span></div><div class="shell editorial-hero-grid"><div><p class="section-index">Legal draft</p><h1>{title}</h1></div><p>{desc}</p></div></section><section class="editorial-section light"><div class="shell editorial-grid"><p class="section-index">Review required</p><div class="editorial-copy">{body}</div></div></section></main>{footer(prefix)}</body></html>'''

def write(route,content):
    dest=ROOT/route/'index.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(content)

def plan(name,route,status='Complete'):
    slug=route.replace('/','-').strip('-');(ROOT/'project-management'/'pages'/f'content-{slug}.md').write_text(f'# {name}\n\n**Route:** `/{route}/`  \n**Status:** {status}\n\n## Phase verification\n\n- Design plan and section hierarchy complete\n- Custom static design complete\n- Original SEO-oriented content complete\n- Semantic architecture and internal links verified\n- Prototype noindex retained until business and production verification\n')

if __name__=='__main__':
    write('about',shell_page('about',PAGES['about']));plan('About','about')
    write('contact',contact_page(False));plan('Contact','contact')
    write('start-a-project',contact_page(True));plan('Start a project','start-a-project')
    write('insights',insights_index());plan('Insights index','insights')
    for g in GUIDES: write(f'insights/{g["slug"]}',guide_page(g));plan(g['title'],f'insights/{g["slug"]}')
    write('privacy',legal_page('privacy'));plan('Privacy policy','privacy','Draft complete; legal review required')
    write('terms',legal_page('terms'));plan('Terms of use','terms','Draft complete; legal review required')
    print('Built core, insight and legal static pages.')
